### ISSUE TITLE
Image seems broken: "unknown command /etc/docker/registry/config.yml"

### ISSUE THREAD

**Issue by tomasaschan** [cblomart/rpi-registry#2]
When I try to run this image on my RPi, the registry fails to start:

```
$ docker run -p5000:5000 cblomart/rpi-registry
Error: unknown command "/etc/docker/registry/config.yml"
Run 'registry help' for usage.
```

Am I misunderstanding something about the usage of this image?

**Comment by ulm0** [comment]
I faced this issue as well, that's why i forked this project then based the image on Alpine as in the official one, you can check the PR i opened #1

**Comment by cblomart** [comment]
I'll look it up.
Sorry for the lack of feedback, I didn't have much time on my hand lately!

**Comment by ulm0** [comment]
Alright got it working, by adding `serve` to the `CMD` layer, gonna open a PR

```Dockerfile
CMD ["serve", "/etc/docker/registry/config.yml"]
```
