### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by axxeth** [cblomart/rpi-registry#4]
I have been figuring out how to use this ( haven't yet found out what is the catch, started with docker today)

Seems that I can't just pull this into my docker and then run it?

Do I need to clone this as git repo and then build it somehow (with those make commands etc) ?

As a reference, this rpi registry worked ok, however it has only v1 support and does not work with latest docker.

```
docker run \
    --name registry \
    -p 5000:5000 \
    -v ~/dockerregistry/data:/tmp/registry \
    -d \
    -e MIRROR_SOURCE=https://registry-1.docker.io  \
    -e MIRROR_SOURCE_INDEX=https://index.docker.io \
    -e GUNICORN_OPTS=["--preload"] \
    nimblestratus/rpi-docker-registry
```

tried to use this (with cblomart/rpi-registry) and no success:

```
docker run \
    --name registry \
    -p 5000:5000 \
    -v ~/dockerregistry/data:/tmp/registry \
    -d \
    -e MIRROR_SOURCE=https://registry-1.docker.io  \
    -e MIRROR_SOURCE_INDEX=https://index.docker.io \
    -e GUNICORN_OPTS=["--preload"] \
    cblomart/rpi-registry
```

this did not work either:

```
# run cblomart/rpi-registry
docker run -d -p 5000:5000 --restart=always --name registry cblomart/rpi-registry

# login
docker exec -i -t registry /bin/bash

OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
```

**Comment by axxeth** [comment]
Ah, found out some "raw" guide, was able to set up new registry on my pi - however it is not image yet.
Closing :)

"raw" guide was: https://www.ibm.com/developerworks/cloud/library/cl-docker-registry-cache-raspberry-pi/index.html

**Comment by cblomart** [comment]
Glad you found some directions.

I still need to update registry here. nevertheless the image shpuld work with:
```sh
docker run -d -p 5000:5000 --restart=always --name registry cblomart/rpi-registry
```

The thing is: 
As go binaries are self suffisient the container is made from "scratch" in place of a standard distribution like ubuntu or alpine.
For this reason there is no bash in the image.

When you do:
```sh
docker exec -i -t registry /bin/bash
```
It can't find the /bin/bash you are trying to run as it is not in the container.

Registry V1 is a python application that runs via a gunicorn python (wsgi) handler.  It does need all the dependencies (python, gunicorn). In this more complex situation a full image is necessary.

That fact that Registry V2 is in golang, helped create a realy tiny image with only registry in it.
